# var-name = [ "Aman-1","Aman-2" ]
# application_name = "AMAN"
# account_id = 4831365
# incident_preference="PER_POLICY"
# apdex_warning_threshold = 0.8
# apdex_critical_threshold = 0.7
# apdex_duration = 300
# apdex_t = 0.4
# error_rate_warning_threshold = 2
# error_rate_critical_threshold = 5
# error_rate_duration = 300